
# The name of your cluster. It's important to match other New Relic products to relate the data.
cluster_name: "kamon-play-scala-sample"

# How often the integration should run. Defaults to 30s.
# scrape_duration: "30s"

# The HTTP client timeout when fetching data from endpoints. Defaults to 5s.
# scrape_timeout: "5s"

# Whether the integration should run in verbose mode or not. Defaults to false.
verbose: false

# Whether the integration should skip TLS verification or not. Defaults to false.
insecure_skip_verify: false

# The label used to identify scrapable targets. Defaults to "prometheus.io/scrape".
scrape_enabled_label: "prometheus.io/scrape"

# Whether k8s nodes need to be labelled to be scraped or not. Defaults to true.
require_scrape_enabled_label_for_nodes: true

# Uncomment this if you want some staging
#metric_api_url: 'https://staging-metric-api.newrelic.com/metric/v1/infra'

targets:
  - description: Our sick sample app yo
    urls: ["http://staging-kamon-play-scala-sample-9095.vip.cf.nr-ops.net/"]
#    urls: ["http://localhost:9095/"]
# targets:
# - description: Secure etcd example
# urls: ["https://192.168.3.1:2379", "https://192.168.3.2:2379", "https://192.168.3.3:2379"]
# tls_config:
# ca_file_path: "/etc/etcd/etcd-client-ca.crt"
# cert_file_path: "/etc/etcd/etcd-client.crt"
# key_file_path: "/etc/etcd/etcd-client.key"

# Proxy to be used by the emitters when submitting metrics. It should be
# in the format [scheme]://[domain]:[port].
# The emitter is the component in charge of sending the scraped metrics.
# This proxy won't be used when scraping metrics from the targets.
# By default it's empty, meaning that no proxy will be used.
# emitter_proxy: "http://localhost:8888"

# Certificate to add to the root CA that the emitter will use when
# verifying server certificates.
# If left empty, TLS uses the host's root CA set.
# emitter_ca_file: "/path/to/cert/server.pem"

# Whether the emitter should skip TLS verification when submitting data.
# Defaults to false.
# emitter_insecure_skip_verify: false

# Histogram support is based on New Relic's guidelines for higher
# level metrics abstractions https://github.com/newrelic/newrelic-exporter-specs/blob/master/Guidelines.md.
# To better support visualization of this data, percentiles are calculated
# based on the histogram metrics and sent to New Relic.
# By default, the following percentiles are calculated: 50, 95 and 99.
#
# percentiles:
# - 50
# - 95
# - 99

# transformations: 
#   - description: "Transformation for MySQL exporter" 
#     rename_attributes: 
#       - metric_prefix: "mysql_" 
#         attributes: 
#           table: "tableName" 
#     copy_attributes: 
#       - from_metric: "mysql_version_info" 
#         to_metrics: - "mysql_" 
#         attributes: 
#           - "innodb_version" 
#           - "version" 
#     ignore_metrics: 
#       - except: 
#         - "mysql_"
